### ISSUE TITLE
공지사항 글 확인시 날짜가 제대로 표기되지 않습니다

### ISSUE THREAD

**Issue by yoonyounghoon** [AlbalogTeam/AlbalogClient#84]
![image](https://user-images.githubusercontent.com/45310468/124421982-840d4c00-dd9d-11eb-93c1-e4db0245a52c.png)

**Comment by yoonyounghoon** [comment]
@ksmfou98 확인부탁드려요!

**Comment by ksmfou98** [comment]
이부분 제가 최근 merge부분에 수정했었습니다!! 
영훈님 풀리퀘 하시기전에 머지 받으셨으면 다시 확인해보시겠어요!??
